version: 2.0

references:

  docker_image: &docker_image
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/frontend

  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - repo-v1-{{ .Branch }}-{{ .Revision }}
        - repo-v1-{{ .Branch }}
        - repo-v1

  restore_deps_node: &restore_deps_node
    restore_cache:
      keys:
        - deps_node-v1-{{ .Branch }}-{{ .Revision }}
        - deps_node-v1-{{ .Branch }}
        - deps_node-v1

  deps_node_key: &deps_node_key
    node-deps-v1-{{ checksum "package.json" }}
  jars_backup_cache_key: &jars_backup_cache_key
    node-deps-v1

jobs:
  checkout_code:
    <<: *docker_image
    steps:
      - *restore_repo
      - *restore_deps_node
      - checkout
      - save_cache:
          key: repo-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  node_dependencies:
    <<: *docker_image
    steps:
      - *restore_repo
      - run:
          command: lein deps
      - save_cache:
          key: *deps_node_key
          paths:
            - /root/.m2

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - checkout_code
      - node_dependencies:
          requires:
            - checkout_code
      - npm_bower_dependencies:
          requires:
            - checkout_code