version: 2.0

references:

  docker_image: &docker_image
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/frontend

  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - repo-v1-{{ .Branch }}-{{ .Revision }}
        - repo-v1-{{ .Branch }}
        - repo-v1

  restore_deps_node: &restore_deps_node
    restore_cache:
      keys:
        - deps_node-v1-{{ .Branch }}-{{ .Revision }}
        - deps_node-v1-{{ .Branch }}
        - deps_node-v1

  deps_node_key: &deps_node_key
    node-deps-v1-{{ checksum "package.json" }}

  restore_deps_bower: &restore_deps_bower
    restore_cache:
      keys:
        - deps_bower-v1-{{ .Branch }}-{{ .Revision }}
        - deps_bower-v1-{{ .Branch }}
        - deps_bower-v1

  deps_bower_key: &deps_bower_key
    bower-deps-v1-{{ checksum "bower.json" }}

jobs:
  checkout_code:
    <<: *docker_image
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: repo-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  build:
    docker:
      - image: node:10
    steps:
      - *restore_repo
      - *restore_deps_node
      - *restore_deps_bower
      - run:
          command: npm i
      - save_cache:
          key: *deps_node_key
          paths:
            - node_modules
      - run:
          command: npm run bower -- i --allow-root
      - save_cache:
          key: *deps_bower_key
          paths:
            - bower_components
      - run:
          command: npm run grunt
      - *attach_workspace
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./main.css

  release:
    <<: *docker_image
    steps:
      - *restore_repo
      - *attach_workspace
      - run: ci/release.sh

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - release:
          requires:
            - checkout_code
            - build
