version: 2.0

references:

  working_directory: &working_directory
    working_directory: ~/frontend

  docker_image: &docker_image
    docker:
      - image: docker:18.05.0-ce-git

  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  checkout_project: &checkout_project
    checkout:
      path: ~/frontend

  restore_deps_node: &restore_deps_node
    restore_cache:
      keys:
        - deps_node-v1-{{ .Branch }}-{{ .Revision }}
        - deps_node-v1-{{ .Branch }}
        - deps_node-v1

  deps_node_key: &deps_node_key
    node-deps-v1-{{ checksum "package.json" }}

  restore_deps_bower: &restore_deps_bower
    restore_cache:
      keys:
        - deps_bower-v1-{{ .Branch }}-{{ .Revision }}
        - deps_bower-v1-{{ .Branch }}
        - deps_bower-v1

  deps_bower_key: &deps_bower_key
    bower-deps-v1-{{ checksum "bower.json" }}

jobs:
  git_version:
    <<: *docker_image
    steps:
      - run:
          command: git --version

  build:
    <<: *working_directory
    docker:
      - image: node:10
    steps:
      - *checkout_project
      - *restore_deps_node
      - *restore_deps_bower
      - run:
          command: npm i
      - save_cache:
          key: *deps_node_key
          paths:
            - node_modules
      - run:
          command: npm run bower -- i --allow-root
      - save_cache:
          key: *deps_bower_key
          paths:
            - bower_components
      - run:
          command: npm run grunt
      - *attach_workspace
      - persist_to_workspace:
          root: .
          paths:
            - dist

  release:
    <<: *working_directory
    <<: *docker_image
    steps:
      - *checkout_project
      - *attach_workspace
      - run: ci/release.sh

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - git_version
      - build:
          filters:
            tags:
              only:
                - /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only:
                - /^app\/v.*/